### ISSUE TITLE
IOError on run

### ISSUE THREAD

**Issue by knobotz** [deeplearninc/auger-ml#194]
Using latest experimental build (rev 778ce3230ffe21f4190596685e489889a2ec9f09), I get this error running bikesharing hourly dataset:

```sh
[2018-06-13 23:22:39,865: ERROR/ForkPoolWorker-1]: Task auger_ml.AugerMLQueue.evaluate_task[72a58265-7761-40c1-8ff2-659c0879ad8b] raised unexpected:
IOError(22, "invalid mode ('w+') or filename")Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_taskR = retval = fun(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__return self.run(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/auger_ml/AugerMLQueue.py", line 61, in evaluate_taskreturn AugerMLOptimizers(params).evaluate()
File "/usr/local/lib/python2.7/dist-packages/auger_ml/optimizers/AugerMLOptimizers.py", line 123, in evaluateself._preprocess_data()
File "/usr/local/lib/python2.7/dist-packages/auger_ml/optimizers/AugerMLOptimizers.py", line 101, in _preprocess_dataFSClient().writeJSONFile(ds._get_datacache_path("target_categoricals.json"), {})
File "/usr/local/lib/python2.7/dist-packages/auger_ml/FSClient.py", line 80, in writeJSONFile
self.writeTextFile(path, json.dumps(data), atomic=atomic)
File "/usr/local/lib/python2.7/dist-packages/auger_ml/FSClient.py", line 76, in writeTextFileclient.writeTextFile(path, data, atomic=atomic)
File "/usr/local/lib/python2.7/dist-packages/auger_ml/LocalFSClient.py", line 71, in writeTextFilewith self.open(path, "w+") as file:
File "/usr/local/lib/python2.7/dist-packages/auger_ml/LocalFSClient.py", line 83, in open
return open(path, mode)
IOError: [Errno 22] invalid mode ('w+') or filename: '/mnt/workspace/projects/bikesharing/channels/pipeline_channel_9808C05FFA2B4C01B1FA8F51EB8657F5/datacache/target_categoricals.json'
```

**Comment by holyketzer** [comment]
It's quite obvious that distributed systems shouldn't use files for communication between their components

**Comment by skatedplrn** [comment]
Should be fixed now

**Comment by knobotz** [comment]
@skatedplrn sorry I need to re-open this, just saw it happen again this morning on latest experimental stack...

**Comment by skatedplrn** [comment]
We just try to write file on worker node, have no idea why it cannot write file
All folders created before

**Comment by knobotz** [comment]
Does it have something to do with [file truncation](https://stackoverflow.com/questions/16208206/confused-by-python-file-mode-w) perhaps?
