### ISSUE TITLE
Malformed JSON in model_settings posted to Hub API PATCH /api/v1/project_runs/:id

### ISSUE THREAD

**Issue by holyketzer** [deeplearninc/auger-ml#206]
`Infinity` string in `max_total_time_mins`, is not a valid JSON so request can't get inside Rails controller and we can't handle it

https://sentry.io/app71721582herokucom-u7/auger-hub-staging/issues/590113968/?query=is:unresolved

```
{
  "status": "completed",
  "message": "",
  "project_api_token": "TEST",
  "model_settings": {
    "status": "completed",
    "start_time": "2018-06-26 09:07:32.714791",
    "total_evaluations": 6,
    "evaluation_options": {
      "classification": true,
      "data_path": "tests/fixtures/nba_player_games_small.csv",
      "max_eval_time_mins": 1,
      "deadline": null,
      "targetFeature": "team_id",
      "tasks_run_parallel": false,
      "evaluate_task_id": null,
      "scoring": "accuracy",
      "algorithms_run_parallel": false,
      "data_folds_path": [
        "/var/src/auger-ml-worker/auger_ml/tests/temp/channels/test_ensembles/datacache/traindata_fold0.npz",
        "/var/src/auger-ml-worker/auger_ml/tests/temp/channels/test_ensembles/datacache/traindata_fold1.npz",
        "/var/src/auger-ml-worker/auger_ml/tests/temp/channels/test_ensembles/datacache/traindata_fold2.npz"
      ],
      "project_run_id": "C48334599D104F4",
      "data_folds_path_prefix": "/var/src/auger-ml-worker/auger_ml/tests/temp/channels/test_ensembles/datacache/traindata_fold",
      "top_pipelines_limit": 10,
      "crossValidationFolds": 3,
      "ensemble": false,
      "max_n_trials_algorithms": 2,
      "search_space_ensembles": {
        "auger_ml.ensembles.algorithms.SuperLearnerAlgorithm": {
          "method": "lbfgs",
          "classification": true,
          "opt_trials": 3
        },
        "auger_ml.ensembles.algorithms.VotingAlgorithm": {
          "voting": "soft",
          "weights": null,
          "n_best": 3
        },
        "auger_ml.ensembles.algorithms.GreedySelectionAlgorithm": {
          "improve_eps": false,
          "bag_fraction": 0.5,
          "max_bag_pipelines": 3,
          "random_state": 12345,
          "prune_fraction": 0,
          "n_bags": 3,
          "n_best": 1
        },
        "auger_ml.ensembles.algorithms.AveragingAlgorithm": {
          "weights": null,
          "n_best": 3,
          "classification": true
        }
      },
      "optimizers_run_parallel": false,
      "originalFeatureColumns": [
        "points",
        "offensive_rebounds",
        "defensive_rebounds",
        "assists",
        "steals",
        "blocks",
        "turnovers",
        "field_goals_att",
        "three_points_att",
        "two_points_att",
        "personal_fouls",
        "minutes"
      ],
      "scoreNames": [
        "accuracy",
        "neg_log_loss",
        "f1_micro",
        "f1_macro",
        "f1_weighted",
        "precision_micro",
        "precision_macro",
        "precision_weighted",
        "recall_micro",
        "recall_macro",
        "recall_weighted"
      ],
      "augerInfo": {
        "projectChannelPath": "/var/src/auger-ml-worker/auger_ml/tests/temp/channels/test_ensembles",
        "predictionsPath": "/var/src/auger-ml-worker/auger_ml/tests/temp/channels/test_ensembles/project_runs/C48334599D104F4/predictions",
        "datacachePath": "/var/src/auger-ml-worker/auger_ml/tests/temp/channels/test_ensembles/datacache",
        "metricsPath": "/var/src/auger-ml-worker/auger_ml/tests/temp/channels/test_ensembles/metrics",
        "pipelinesPath": "/var/src/auger-ml-worker/auger_ml/tests/temp/channels/test_ensembles/project_runs/C48334599D104F4/pipelines",
        "evaluationRunPath": "/var/src/auger-ml-worker/auger_ml/tests/temp/channels/test_ensembles/project_runs/C48334599D104F4",
        "tmpPath": "/var/src/auger-ml-worker/auger_ml/tests/temp",
        "projectPath": "/var/src/auger-ml-worker/auger_ml/tests/temp",
        "modelsPath": "/var/src/auger-ml-worker/auger_ml/tests/temp/models",
        "channel": "test_ensembles"
      },
      "dataset_manifest_id": "5822A3B19B7C487",
      "featureColumns": [
        "points",
        "offensive_rebounds",
        "defensive_rebounds",
        "assists",
        "steals",
        "blocks",
        "turnovers",
        "field_goals_att",
        "three_points_att",
        "two_points_att",
        "personal_fouls",
        "minutes"
      ],
      "max_total_time_mins": Infinity,
      "max_n_trials": 6
    },
    "end_time": "2018-06-26 09:07:36.180232",
    "dataset_manifest_id": "5822A3B19B7C487"
  }
}
```

cc @knobotz 

Can be related to https://github.com/deeplearninc/auger-ml/issues/142

**Comment by holyketzer** [comment]
Ruby
```ruby
> JSON.parse('{"max_total_time_mins": Infinity}')
JSON::ParserError: 230: unexpected token at ' Infinity}'
	from (irb):21
```

JS
```JS
JSON.parse('{"max_total_time_mins": Infinity}')
SyntaxError: JSON Parse error: Unexpected identifier "Infinity"
parse
Global Code
evaluateWithScopeExtension
_evaluateOn
_evaluateAndWrap

```

Python
```python
json.loads('{"max_total_time_mins": Infinity}')
{u'max_total_time_mins': inf}
```

I think JS is reference implementation of JSON, because it's JS native data format.

It's possible to enforce Infinity serialisation in serialiser with `allow_nan=False`
```python
>>> json.dumps({u'max_total_time_mins': float('inf')})
'{"max_total_time_mins": Infinity}'
>>> json.dumps({u'max_total_time_mins': float('inf')}, allow_nan=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
```
