### ISSUE TITLE
Creating new account and loading first datasource for auger-notebook error

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ml#214]
1) Create new Project
2) Start cluster
3) Select datasource bike_sample_example.csv from local file tab

For some reason celery task cancels. It works if you refresh and try again but happens on users first time onboarding which is very bad.

ERROR:root:
Traceback (most recent call last):
  File "auger_notebook/models/regression/slamm.py", line 305, in load_source_file
    self.table.value = self.collect_dataframe()
  File "auger_notebook/models/regression/slamm.py", line 445, in collect_dataframe
    res = self.df.getStatistics()
  File "/usr/local/lib/python2.7/dist-packages/auger_ml/data_source/data_source_api.py", line 52, in getStatistics
    return self.run_ds_method("getStatistics")
  File "/usr/local/lib/python2.7/dist-packages/auger_ml/data_source/data_source_api_pandas_proxy.py", line 17, in run_ds_method
    res = AugerMLQueue(self.options).execute_datasource_task(params, self.sync_mode)
  File "/usr/local/lib/python2.7/dist-packages/auger_ml/AugerMLQueue.py", line 87, in execute_datasource_task
    return self._execute_tasks([task], datasource_task, wait_for_result)
  File "/usr/local/lib/python2.7/dist-packages/auger_ml/base_tasks_queue.py", line 99, in _execute_tasks
    raise TasksCanceled(self)
TasksCanceled

**Comment by derekflint** [comment]
This bug can be reproduced everytime a new organization is created and then a new projects first run. Unfortunately it works after that first failure so its hard to repro.  The main issue is that every new user will run into this

**Comment by derekflint** [comment]
I think issue is when cluster comes up first time celery workers aren't ready, call to collect() then times out.

**Comment by skatedplrn** [comment]
should be fixed now

**Comment by derekflint** [comment]
looks good now
