### ISSUE TITLE
Categorical features arer still converted to float when read from file

### ISSUE THREAD

**Issue by jetsnguns** [deeplearninc/auger-ml#275]
Example: https://app.auger.ai/auger/projects/alex-f-test
There are errors while reading the data after assigning column types in UI and before running preprocessors. There should be no need to convert all columns to float.
```
[2018-08-15 20:47:57,388: WARNING/ForkPoolWorker-1]: could not convert string to float: P9HTde2
[2018-08-15 20:47:57,398: WARNING/ForkPoolWorker-1]: could not convert string to float: _VHQRHe
[2018-08-15 20:47:57,404: WARNING/ForkPoolWorker-1]: could not convert string to float: smXZ
[2018-08-15 20:47:57,419: WARNING/ForkPoolWorker-1]: could not convert string to float: e9dM
[2018-08-15 20:47:57,435: WARNING/ForkPoolWorker-1]: invalid literal for float(): 9_Y1
[2018-08-15 20:47:57,450: WARNING/ForkPoolWorker-1]: could not convert string to float: VpdQ
[2018-08-15 20:47:57,464: WARNING/ForkPoolWorker-1]: could not convert string to float: IYzP
[2018-08-15 20:47:57,479: WARNING/ForkPoolWorker-1]: could not convert string to float: kIsH
[2018-08-15 20:47:57,494: WARNING/ForkPoolWorker-1]: could not convert string to float: vdKemiX
[2018-08-15 20:47:57,510: WARNING/ForkPoolWorker-1]: could not convert string to float: k0HX
[2018-08-15 20:47:57,523: WARNING/ForkPoolWorker-1]: could not convert string to float: cJvF
[2018-08-15 20:47:57,536: WARNING/ForkPoolWorker-1]: could not convert string to float: FzaX
[2018-08-15 20:47:57,556: WARNING/ForkPoolWorker-1]: could not convert string to float: LM8l689qOp
[2018-08-15 20:47:57,566: WARNING/ForkPoolWorker-1]: could not convert string to float: ELof
[2018-08-15 20:47:57,579: WARNING/ForkPoolWorker-1]: could not convert string to float: am7c
[2018-08-15 20:47:57,616: ERROR/ForkPoolWorker-1]: AugerMLOptimizers::_preprocess_data failed.Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/auger_ml/optimizers/AugerMLOptimizers.py", line 311, in evaluatewarnings = self._preprocess_data()
File "/usr/local/lib/python2.7/dist-packages/auger_ml/optimizers/AugerMLOptimizers.py", line 284, in _preprocess_datapreprocessors = self._run_preprocessors(ds, categoricals, target)
File "/usr/local/lib/python2.7/dist-packages/auger_ml/optimizers/AugerMLOptimizers.py", line 124, in _run_preprocessorsds.df = pp.fit_transform(ds.df[self.options['featureColumns']])
File "/usr/local/lib/python2.7/dist-packages/auger_ml/preprocessors/pipeline.py", line 119, in fit_transformdf = w.fit_transform(df)
File "/usr/local/lib/python2.7/dist-packages/auger_ml/preprocessors/pipeline.py", line 35, in fit_transformraise PipelineException(self.name, self.params, e)
PipelineException
[2018-08-15 20:47:58,111: INFO/ForkPoolWorker-1]: Task auger_ml.AugerMLQueue.evaluate_task
[fdfe347c-8829-436a-9100-5511714aa056] succeeded in 7.242876159s: ('f1', None)
[I 20:48:02.003 NotebookApp]: []
```

**Comment by skatedplrn** [comment]
This is issue with NanPreprocessor.
run:
pytest -s ./tests/test_auger_ml_optimizers.py::TestAugerMLOptimizers::test_categoricals_NAN
see in the log:
INFO:root:NanPreprocessor impute mean failed for col 'v3':could not convert string to float: C

**Comment by khizanov** [comment]
Bug is not reproducible in #336
The error is caused if user marked categorical column as numeric.

**Comment by jetsnguns** [comment]
Run `tests/test_auger_ml_optimizers.py::TestAugerMLOptimizers::test_evaluate_metafeatures` from here: https://github.com/deeplearninc/auger-ml/commit/a1f5e3afc661abd7d17a64f6f818bee27ba86b76 
Log:
```nan.py                      40 INFO     NanPreprocessor impute mean failed for col 'v3':could not convert string to float: C
nan.py                      40 INFO     NanPreprocessor impute mean failed for col 'v22':could not convert string to float: QKI
nan.py                      40 INFO     NanPreprocessor impute mean failed for col 'v30':could not convert string to float: C
nan.py                      40 INFO     NanPreprocessor impute mean failed for col 'v31':could not convert string to float: A
nan.py                      40 INFO     NanPreprocessor impute mean failed for col 'v52':could not convert string to float: G
nan.py                      40 INFO     NanPreprocessor impute mean failed for col 'v56':could not convert string to float: DA
nan.py                      40 INFO     NanPreprocessor impute mean failed for col 'v91':could not convert string to float: F
nan.py                      40 INFO     NanPreprocessor impute mean failed for col 'v107':could not convert string to float: A
nan.py                      40 INFO     NanPreprocessor impute mean failed for col 'v112':could not convert string to float: A
nan.py                      40 INFO     NanPreprocessor impute mean failed for col 'v113':could not convert string to float: G
nan.py                      40 INFO     NanPreprocessor impute mean failed for col 'v125':could not convert string to float: V```
