### ISSUE TITLE
Customer Issue 

### ISSUE THREAD

**Issue by derekflint** [deeplearninc/auger-ml#297]
Issue loading dataset.

File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 440, in _readparser = TextFileReader(filepath_or_buffer, **kwds)File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 787, in __init__self._make_engine(self.engine)File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1014, in _make_engineself._engine = CParserWrapper(self.f, **self.options)File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1749, in __init___validate_usecols_names(usecols, self.orig_names)File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1134, in _validate_usecols_names"columns expected but not found: {missing}".format(missing=missing)ValueError: Usecols do not match columns, columns expected but not found: [' I21 ', ' I25 ', ' I1 '][2018-08-31 12:06:38,211: ERROR/ForkPoolWorker-1]: Call HubApiClient failed. Method: update_project_run. Params: {'status': 'completed', 'message': '', 'id': 'E99589D25175410', 'model_settings': {'status': 'completed', u'errors': {u'error': u"Usecols do not match columns, columns expected but not found: [' I21 ', ' I25 ', ' I1 ']"}, 'end_time': '2018-08-31 12:06:37.768769', 'total_evaluations': 1000}}Traceback (most recent call last):File "/usr/local/lib/python2.7/dist-packages/auger_ml/auger_messenger.py", line 157, in _send_to_hubres = getattr(client, method)(**params)File "/usr/local/lib/python2.7/dist-packages/auger/hub_api_client.py", line 234, in updatereturn self.make_and_handle_request('patch', path, kwargs)File "/usr/local/lib/python2.7/dist-packages/auger/hub_api_client.py", line 129, in make_and_handle_requestreturn self.handle_response(res)File "/usr/local/lib/python2.7/dist-packages/auger/hub_api_client.py", line 105, in handle_responseraise self.FatalApiError(self.format_response(res))FatalApiError: status: 404, body: {"meta":{"status":404,"errors":[{"message":"Couldn't find ExperimentSession","error_type":"not_found"}]}}[2018-08-31 12:06:38,220: INFO/ForkPoolWorker-1]: Task auger_ml.AugerMLQueue.evaluate_task[6c25e313-b59b-4fe1-bd1c-644e88af519d] succeeded in 2.128334542s: ('accuracy', None)

**Comment by knobotz** [comment]
Moved this over to issues.
